apiVersion: aws.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: aws-kosmos-sbx
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane
      name: aws-secret
      key: creds
  assumeRoleChain:
    - roleARN: arn:aws:iam::682033478562:role/controllers.cluster-api-provider-aws.sigs.k8s.io
