apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: observability-apps
spec:
  goTemplate: true
  goTemplateOptions: [ "missingkey=error" ]
  generators:
  - list:
      elements:
      - name: metrics-server
        serverSideApply: true
        namespace: kube-system
      - name: keda
        namespace: keda
        serverSideApply: true
      - name: kube-prometheus-stack
        namespace: observability
        serverSideApply: true
      - name: prometheus-rules
        namespace: observability
        serverSideApply: true
      - name: grafana
        namespace: observability
        serverSideApply: true
      - name: loki-stack
        namespace: observability
        serverSideApply: true
      - name: thanos
        namespace: observability
        serverSideApply: true
      - name: cloudnative-pg-operator
        namespace: cloudnative-pg
        serverSideApply: true
      - name: cloudnative-pg-cluster
        namespace: cloudnative-pg
        serverSideApply: true
  template:
    metadata:
      name: "{{ .name }}"
      annotations:
        argocd.argoproj.io/manifest-generate-paths: "."
        # notifications.argoproj.io/subscribe.on-sync-succeeded.telegram: "-1001726711150"
        argocd.argoproj.io/compare-options: '{{ printf "%s=%s" "ServerSideDiff" (dig "serverSideDiff" "true" . | toString) }}'
    spec:
      project: observability
      source:
        repoURL: git@github.com:alcps/kosmos-observability.git
        targetRevision: HEAD
        path: "observability/{{ .name }}"
        # plugin:
        #   name: avp-directory-include
        # env:
        #   - name: FILE_NAME
        #     value: "system/{{ .name }}"
      destination:
        name: in-cluster
        namespace: '{{ default .name (dig "namespace" "" .) }}'
      ignoreDifferences:
      - group: apiextensions.k8s.io
        kind: CustomResourceDefinition
        jqPathExpressions:
        - .spec.conversion.webhook.clientConfig.caBundle
      # FIXME: https://github.com/cloudnative-pg/charts/issues/426
      - group: postgresql.cnpg.io
        kind: Cluster
        jqPathExpressions:
        - .spec.postgresql.pg_hba
        - .spec.postgresql.pg_ident
      - group: apps
        kind: "*"
        jqPathExpressions:
        - .spec.template.spec.hostUsers
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
        - ServerSideApply=true
        - RespectIgnoreDifferences=true
        - PruneLast=true
        - PrunePropagationPolicy=foreground
        - SkipDryRunOnMissingResource=true
        - '{{ printf "%s=%s" "ServerSideApply" (dig "serverSideApply" "true" . | toString) }}'
