apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin-secret
  namespace: observability
type: Opaque
data:
  admin-user: YWRtaW4=
  admin-password: a29zbW9zQGFkbWlu
---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin-secret
  namespace: { ? { .Release.Namespace } }
type: Opaque
stringData:
  admin-user: { ? { .Values.grafana.grafana.adminUser | quote } }
  admin-password: { ? { .Values.grafana.grafana.adminPassword | quote } }

  # Database
  GF_DATABASE_NAME: "grafana"
  GF_DATABASE_HOST: "postgres-v17-c1-rw.databases.svc.cluster.local"
  GF_DATABASE_USER: { ? { .Values.grafana.database.user | quote } }
  GF_DATABASE_PASSWORD: { ? { .Values.grafana.database.password | quote } }

  # Database Init
  INIT_POSTGRES_DBNAME: "grafana"
  INIT_POSTGRES_HOST: "postgres-v17-c1-rw.databases.svc.cluster.local"
  INIT_POSTGRES_USER: { ? { .Values.grafana.database.user | quote } }
  INIT_POSTGRES_PASS: { ? { .Values.grafana.database.password | quote } }
  INIT_POSTGRES_SUPER_PASS: { ? { .Values.grafana.database.superuserPassword | quote } }
