apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  admin-user: grafana
  admin-password: grafana

  # Database
  GF_DATABASE_NAME: "app"
  GF_DATABASE_HOST: "cloudnative-pg-cluster-rw.cloudnative-pg.svc.cluster.local"
  GF_DATABASE_USER: postgres
  GF_DATABASE_PASSWORD: kosmos@admin

  # Database Init
  INIT_POSTGRES_DBNAME: "grafana"
  INIT_POSTGRES_HOST: "cloudnative-pg-cluster-rw.cloudnative-pg.svc.cluster.local"
  INIT_POSTGRES_USER: postgres
  INIT_POSTGRES_PASS: eezyH1iv7ldvH6yWEgFqCJkj6EvlPfbaEt53SKHcjZoekUTD4bWV8I89nKJlvulJ
  INIT_POSTGRES_SUPER_PASS: eezyH1iv7ldvH6yWEgFqCJkj6EvlPfbaEt53SKHcjZoekUTD4bWV8I89nKJlvulJ